#!/bin/sh

# This script attempts to copy over a Chrome extension Native Messaging Host
# manifest file to the correct location on a user's filesystem. That
# location depends on the platform. Below you can find documentation copied
# directly from https://developer.chrome.com/extensions/messaging#native-messaging-host
# which explains where these locations are.

# Windows
# -------
# The manifest file can be located anywhere in the file system. The application
# installer must create one of the following registry keys
#   - HKEY_LOCAL_MACHINE\SOFTWARE\Google\Chrome\NativeMessagingHosts\com.my_company.my_application
#   - HKEY_CURRENT_USER\SOFTWARE\Google\Chrome\NativeMessagingHosts\com.my_company.my_application
# and set default value of that key to the full path to the manifest file.  #

# OSX
# ---
# The manifest file must be placed at either
#   - /Library/Google/Chrome/NativeMessagingHosts/com.my_company.my_application.json
#   - ~/Library/Application Support/Google/Chrome/NativeMessagingHosts/com.my_company.my_application.json

# Linux
# -----
# The manifest file must be placed at either
#   - /etc/opt/chrome/native-messaging-hosts/com.my_company.my_application.json
#   - ~/.config/google-chrome/NativeMessagingHosts/com.my_company.my_application.json

CURRENT=`pwd`
# NPM-install all the necessary node modules for the host script.
echo "Installing npm  modules for listener script"
cd host
npm install

# Change back to the root dir
cd ${CURRENT}
MANIFEST_FILENAME="org.vim.stayfresh.json"
# Change the placeholder text in the templatized manifest file to the
# correct path and write the result to the correct place in the filesystem.
# TODO: Install in different locations depending on host OS.
sed "s|PATH_TO_EXTENSION|${CURRENT}|" host/${MANIFEST_FILENAME} > ~/Library/Application\ Support/Google/Chrome/NativeMessagingHosts/${MANIFEST_FILENAME}
echo "Copying native messaging host manifest to ~/Library/Application\ Support/Google/Chrome/NativeMessagingHosts/${MANIFEST_FILENAME}"

# Cat it out for confirmation.
cat ~/Library/Application\ Support/Google/Chrome/NativeMessagingHosts/${MANIFEST_FILENAME}
echo "You should see the correct manifest file contents printed out above. If not, something probably went wrong."
